### ISSUE TITLE
Add a drag event

### ISSUE THREAD

**Issue by theVivern** [rio-project/rio#46]
- on the JS side
- on the Python side

Then make use of it, e.g. in the volume slider of the media player

**Comment by Aran-Fey** [comment]
I've added a basic implementation, but there is a surprising amount of design decisions that need to be made.

In python:

1. Is a `on_drag` event enough or do we need `on_drag_start`, `on_drag_move`, and `on_drag_end`?
2. Should the coordinates be relative to the viewport, the `MouseEventListener`, or maybe something else?
3. The `MouseDragEvent` includes the components that the event started and ended on, but what if those components are internal? (Like `_ButtonInternal` or `FundamentalRootComponent` or a `Row` created by a high-level `rio.Button`)

In TS:

1. Should the coordinates be clamped to the `clientRect` of the element?
2. Should `stopPropagation()` be called on the event?
